version: '0.1.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
clone_depth: 1
before_build:
  - cmd: choco install opencover.portable
  - cmd: choco install codecov
  - nuget restore .\src\PathEditor.sln
build:
  project: .\src\PathEditor.sln
after_test:
  - cmd: OpenCover.Console.exe -register:user -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:"test ./src/PathEditor.UnitTests" -output:".\PathEditor_coverage.xml" -oldstyle
  - cmd: codecov -f "PathEditor_coverage.xml"
deploy: off
